### ISSUE TITLE
Laravel 5.4 social login Error

### ISSUE THREAD

**Issue by iamarunp** [lahaxearnaud/laravel-u2f#12]
(1/1) FatalThrowableErrorCall to undefined method Illuminate\Session\Store::set()
--
in AbstractProvider.php (line 143)
at AbstractProvider->redirect()

When We search about it we can find that

 link :https://stackoverflow.com/questions/42126827/a-session-error-after-updating-to-laravel-5-4
I solve it, for more information read this: https://laravel.com/docs/5.4/upgrade

All calls to the ->set() method should be changed to ->put(). Typically, Laravel applications would never call the set method since it has never been documented within the Laravel documentation. However, it is included here out of caution.

pls help in solving it with a permenant solution

**Comment by lahaxearnaud** [comment]
Already reported in #8
