### ISSUE TITLE
Call to undefined method Illuminate\Session\Store::first() in the login page

### ISSUE THREAD

**Issue by gouseferoz** [lahaxearnaud/laravel-u2f#26]
I am using Laravel 5.7. In the login page, when i hit login without any value in the form, i see this error.

I also see this when i provide some data in it too. It used to work well I dont know what's causing it.

![image](https://user-images.githubusercontent.com/33931332/60124674-cdd2fd00-97a7-11e9-88c5-1cbea2f031e1.png)

**Comment by lahaxearnaud** [comment]
Hello @gouseferoz,

Are you sure that the issue is related to laravel-u2f ?
The auth/login.blade.php file is not provided by this package.

What version of laravel-u2f are you using ? `composer why lahaxearnaud/laravel-u2f`

Arnaud

**Comment by lahaxearnaud** [comment]
I can't reproduce your issue.

You can take a look at the project [lahaxearnaud/laravel-u2f-example](https://github.com/lahaxearnaud/laravel-u2f-example).

Perhaps I miss the point.

Arnaud
