### ISSUE TITLE
"The visited URL doesn’t match the App ID or your are tot using HTTPS"

### ISSUE THREAD

**Issue by simplenotezy** [lahaxearnaud/laravel-u2f#5]
I am getting the error: `The visited URL doesn’t match the App ID or your are tot using HTTPS` when visiting `u2f/auth`
![image](https://user-images.githubusercontent.com/3786627/27879689-b897c6ae-61c2-11e7-937c-6ba57d06f8f8.png)

**Comment by simplenotezy** [comment]
Could it be because my tld is `app`?

**Comment by lahaxearnaud** [comment]
Hello,

Yes it may be the reason.
Try to change your tld to something like: app.com

Do you use https ?

**Comment by simplenotezy** [comment]
Yes I use https. I'll try that and get back to you.

**Comment by lahaxearnaud** [comment]
it's ok now ?

**Comment by simplenotezy** [comment]
Yes
