### ISSUE TITLE
"A non-numeric value encountered" when running vendor publish

### ISSUE THREAD

**Issue by simplenotezy** [lahaxearnaud/laravel-u2f#6]
I just tried installing this library on a fresh laravel 5.5 installation.

When running `$ php artisan vendor:publish --provider="Lahaxeanaud\U2f\U2fServiceProvider" --tag=config` I get the following error: `[ErrorException] A non-numeric value encountered`

![image](https://user-images.githubusercontent.com/3786627/31174567-38dc85f8-a90c-11e7-9d0f-813aba9672c6.png)

**Comment by simplenotezy** [comment]
Found it:

![image](https://user-images.githubusercontent.com/3786627/31174657-a230b312-a90c-11e7-9971-52833675a1ec.png)

For some reason there is two plusses.

**Comment by lahaxearnaud** [comment]
I never test this package with laravel 5.5. You may have some errors

**Comment by simplenotezy** [comment]
Fixed here, https://github.com/lahaxearnaud/laravel-u2f/pull/11/files#diff-27a26fa774b96db0a49fc46cd3f3c146
