### ISSUE TITLE
Call to undefined method Illuminate\Session\Store::set()

### ISSUE THREAD

**Issue by simplenotezy** [lahaxearnaud/laravel-u2f#8]
I am getting the following error:

![image](https://user-images.githubusercontent.com/3786627/31175864-0a110b40-a911-11e7-969d-01a9a3320de0.png)

Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_ERROR)
Call to undefined method Illuminate\Session\Store::set()

**Comment by simplenotezy** [comment]
Replacing

     \Session::set('u2f.registerData', $req);

WIth

    session(['u2f.registerData' => $req]);

Works

**Comment by lahaxearnaud** [comment]
What laravel version are you using ?

**Comment by simplenotezy** [comment]
Latest version, `5.5.*`

**Comment by jebog** [comment]
use `session(['u2f.registerData' => $req]);` instead of ` \Session::set('u2f.registerData', $req);` or `session()->set('foo', 'bar')`

**Comment by leksoft** [comment]
set -> put

**Comment by ghost** [comment]
Which file do I have to edit??

for

 \Session::set('u2f.registerData', $req); → session(['u2f.registerData' => $req]);

**Comment by owenvoke** [comment]
I guess this was fixed in #11 (v1.0.0)?
